### ISSUE TITLE
why the code taste too much time in the make_cam.py?

### ISSUE THREAD

**Issue by YuYue26** [jieqin-ai/AMR#7]

**Comment by TAILEMI** [comment]
So do I. I wonder how long did it take you to run this code?

**Comment by TAILEMI** [comment]
> _No description provided._

So do I. I wonder how long did it take you to run this code?

**Comment by jieqin-ai** [comment]
We need to generate cams for the two branches separately,  and then perform a weighted summation. So it is time-consuming.

**Comment by YuYue26** [comment]
> > _No description provided._
> 
> So do I. I wonder how long did it take you to run this code?

over a 50h when i use 3090Ti
